Play travis
Otus-DevOps-2019-11/9868-08_infra pull request #1
Opened 2019-12-21 09:48 UTC by 9868-08

play-travis into master

2019-12-22 19:52 UTC, mrgreyves requested changes
Здравствуйте! Возвращаю на доработку. Проверьте комментарии к файлам.

2019-12-22 19:52 UTC, mrgreyves commented on test.txt
> +test
Вот этот файл нужно удалить.

2019-12-22 19:52 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
А вот тут нужно починить тесты =)

2019-12-23 05:52 UTC, 9868-08 reviewed
got it

2019-12-23 08:45 UTC, closed without merging